Process RPC files with CMake. Related bug fixes.
oci-labs/rosidl_typesupport_opendds pull request #32
Opened 2020-06-10 13:58 UTC by kuznetsovmoci

# Description

Process RPC files with CMake. Related bug fixes.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

2020-06-10 16:21 UTC, iguessthislldo commented
See https://github.com/objectcomputing/OpenDDS/pull/1728 for C++11 mapping support for `OPENDDS_TARGET_SOURCES`.

2020-06-10 19:24 UTC, iguessthislldo requested changes

2020-06-10 19:24 UTC, iguessthislldo commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
> +OPENDDS_TARGET_SOURCES(${PROJECT_NAME} include/rosidl_typesupport_opendds_cpp/RPC.idl OPENDDS_IDL_OPTIONS "-Sa -St -Lc++11")
```suggestion
OPENDDS_TARGET_SOURCES(${PROJECT_NAME} include/rosidl_typesupport_opendds_cpp/RPC.idl OPENDDS_IDL_OPTIONS "-Sa" "-St" "-Lc++11")
```

This can't be a single string because `OPENDDS_TARGET_SOURCES` parses `OPENDDS_IDL_OPTIONS` arguments as individual arguments to the CMake function. This would be okay for arguments that `OPENDDS_TARGET_SOURCES` isn't looking, like `-Sa`, but it's probably safer to break them up like they would come up in `argv`.

2020-06-10 19:24 UTC, iguessthislldo commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
>  OPENDDS_TARGET_SOURCES(${PROJECT_NAME} src/identifier.cpp src/wstring_conversion.cpp)
```suggestion
add_library(${PROJECT_NAME} SHARED src/identifier.cpp src/wstring_conversion.cpp)
```

I would prefer vanilla CMake when ever possible. I don't really even like that this is possible. This also stops CMake from complaining about the library not having sources in this case.

2020-06-10 19:35 UTC, iguessthislldo commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
> +OPENDDS_TARGET_SOURCES(${PROJECT_NAME} include/rosidl_typesupport_opendds_cpp/RPC.idl OPENDDS_IDL_OPTIONS "-Sa -St -Lc++11")
Actually after playing around with a test I discovered the single string won't work at all because it's passing the arguments on literally, so in the case of `"-Sa -St"` it errors:

```
IDL: I don't understand the '-Sa -St' option
Use "-h" or "--help" to see valid options.
```

2020-06-12 15:16 UTC, kuznetsovmoci commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
> +OPENDDS_TARGET_SOURCES(${PROJECT_NAME} include/rosidl_typesupport_opendds_cpp/RPC.idl OPENDDS_IDL_OPTIONS "-Sa -St -Lc++11")
Fixed

2020-06-12 15:22 UTC, kuznetsovmoci commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
>  OPENDDS_TARGET_SOURCES(${PROJECT_NAME} src/identifier.cpp src/wstring_conversion.cpp)
With this approach, as we have found, OpenDDS settings (like the one for OpenDDS security) do not get forwarded to the library. So we decided to use OPENDDS_TARGET_SOURCES to add files wherever 'add_library' is used in this project.

2020-06-12 15:41 UTC, mitza-oci approved these changes

2020-06-12 15:41 UTC, adamsj-ros approved these changes

2020-06-12 15:41 UTC, merged

2020-06-12 15:53 UTC, iguessthislldo commented on rosidl_typesupport_opendds_cpp/CMakeLists.txt
>  OPENDDS_TARGET_SOURCES(${PROJECT_NAME} src/identifier.cpp src/wstring_conversion.cpp)
I have already discussed this with Adam and this is a bug in the module. `OPENDDS_TARGET_SOURCES` should just process IDL files, nothing more.